canonical/kubeflow-rocks

volumes-web-app/rockcraft.yaml

This PR is a fix for this https://github.com/canonical/kubeflow-rocks/pull/6
Add rock for volumes web app.
How to build.
```
rockcraft clean && rockcraft pack --verbosity=trace 
sudo skopeo --insecure-policy copy oci-archive:volumes-web-app_v1.7.0_1_amd64.rock docker-daemon:volumes-web-app_v1.7.0_1_amd64.rock:rock
docker run volumes-web-app_v1.7.0_1_amd64.rock:rock  
```

KF-2254 Volumes Web App Rock

---

notebook-controller/rockcraft.yaml

- Added security team recommendations.
- Updated non-root user.

feat: notebook-controller rock

---

jupyter-pytorch-full/rockcraft.yaml

- Added sercurity requirements.
- Updated packages.

feat: jupyter-pytorch-full rock update

---

jupyter-pytorch-cuda-full/rockcraft.yaml

- Added security requirements and updated non-root user.
Based on #3

Kf 2267 feat jupyter pytorch cuda full rock

---

jupyter-web-app/rockcraft.yaml
volumes-web-app/rockcraft.yaml

Jupyter Web App ROCK was developed during workshop.
It needed to be brought up to best practices spec.
https://github.com/canonical/kubeflow-rocks/issues/41
- Added run-user non-root user setup
- Remove old non-user setup.
- Update sequrity team requirements.
- Re-implemented as multi-part rock.
Test run shows that server starts up. It fails due to lack of K8S configuration. This will be addressed in integration stage.
```
ocker run jupyter-web-app_v1.7.0_20.04_1:v1.7.0_20.04_1 exec pebble exec bash -c 'export PYTHONPATH=/ && gunicorn -w 3 --bind 0.0.0.0:5000 --access-logfile - entrypoint:app'
2023-08-21T18:05:08.084Z [pebble] Started daemon.
2023-08-21T18:05:08.097Z [pebble] POST /v1/exec 12.419942ms 202
2023-08-21T18:05:08.110Z [pebble] GET …
```

fix: update jupyter web app rock

---

.github/workflows/build_and_publish_rock.yaml

Initial ROCK build and publish workflow. For more details refer to https://github.com/canonical/kubeflow-rocks/issues/50
- ROCK building and publishing workflow using common actions.

feat: initial publish workflow

---

profile-controller/rockcraft.yaml
profile-controller/tests/test_rock.py
profile-controller/tox.ini

---
- Rolled back `source-subdir`
- Added tests

Updated profile-controller

---

kfam/rockcraft.yaml
kfam/tests/test_rock.py
kfam/tox.ini

---
- Rolled back `source-subdir`
- Added tests

Updated kfam

---

centraldashboard/rockcraft.yaml

chore: bump centraldashboard to 1.9.0

---

admission-webhook/rockcraft.yaml
admission-webhook/tests/test_rock.py
admission-webhook/tox.ini

---
- Rolled back source-subdir
- Added tests

Updated `admission-webhook`

---

tensorboard-controller/rockcraft.yaml
tensorboard-controller/tests/test_rock.py
tensorboard-controller/tox.ini

---
- Rolled back source-subdir
- Added tests

Added `tensorboard-controller`

---

volumes-web-app/rockcraft.yaml
volumes-web-app/tests/test_rock.py
volumes-web-app/tox.ini

---
- Rolled back source-subdir
- Added tests

Updated `volumes-web-app`

---

tensorboard-controller/rockcraft.yaml
tensorboard-controller/tests/test_rock.py

Update rockcraft file to be closer to upstream and have an executable at root directory named `manager`.

fix(tensorboard-controller): Create `manager` executable

---

volumes-web-app/rockcraft.yaml

Close https://warthogs.atlassian.net/browse/KF-6846
* Logs from upstream image https://pastebin.canonical.com/p/zpB8sHPW8G/
* Logs from rock https://pastebin.canonical.com/p/YywbPHvDsb/
* I also deployed it in a kubeflow-volumes charm which was to active without any issues in the container

chore: upgrade volumes-web-app to 1.10.0-rc.0

---

tensorboard-controller/rockcraft.yaml

Close https://warthogs.atlassian.net/browse/KF-6825
* Logs from rock https://pastebin.canonical.com/p/F5vcdHnVXW/
* Logs from upstream image https://pastebin.canonical.com/p/qR3F6mSYvM/

chore: upgrade tensorboard-controller to 1.10.0-rc.0

---

profile-controller/rockcraft.yaml

Close https://warthogs.atlassian.net/browse/KF-6837
* Logs from upstream image https://pastebin.canonical.com/p/njn6KmjRGX/
* Logs from rock https://pastebin.canonical.com/p/66Kb6tNqDZ/

chore: upgrade profile-controller to 1.10.0-rc.1

---

tensorboards-web-app/rockcraft.yaml

Close https://warthogs.atlassian.net/browse/KF-6826
* Logs from upstream image https://pastebin.canonical.com/p/x6NncWDRrx/
* Logs from rock https://pastebin.canonical.com/p/CM4F9d9FXz/

chore: upgrade tensorboards-web-app to 1.10.0-rc.0

---

jupyter-web-app/rockcraft.yaml

Close https://warthogs.atlassian.net/browse/KF-6832
* Logs from upstream image https://pastebin.canonical.com/p/g58mbCgxzR/
* Logs from rock https://pastebin.canonical.com/p/TRH24dTSkH/

chore: upgrade jupyter-web-app to 1.10.0-rc.1

---

notebook-controller/rockcraft.yaml

Part of https://warthogs.atlassian.net/browse/KF-6973
My editor complained about not using strings for env vars, so I updated the env var value as well

chore: Update notebook controller to v1.10.0-rc.1

---

centraldashboard/rockcraft.yaml

chore: Update centraldashboard rock to 1.10-rc.1

---

jupyter-scipy/rockcraft.yaml

Closes https://warthogs.atlassian.net/browse/KF-7072
* bump kubectl to 1.31
* build enviornment versions updated
* jupyter scipy requirements version upadted
* addition of `numpy` and `xgboost` to jupyter-scipy requirements

chore: update jupyter-scipy rock to 1.10.0-rc.1

---

volumes-web-app/rockcraft.yaml

No updates [diff](https://www.diffchecker.com/OeB1DVxC/)
Built locally without problems.

chore: update `volumes-web-app` to `v1.10.0`

---

pvcviewer-controller/rockcraft.yaml

No updates [diff](https://www.diffchecker.com/ZJH37nXy/)
Built locally without problems.

chore: update `pvcviewer` to `v1.10.0`

---

jupyter-pytorch-full/rock-ci-metadata.yaml

Closes https://github.com/canonical/kubeflow-rocks/issues/213

feat: rock-ci-metadata.yaml for pytorch-full

---

jupyter-pytorch-full/rockcraft.yaml

Closes https://github.com/canonical/kubeflow-rocks/issues/226

fix: Remove the NB_PREFIX env var in pebble service

---

tensorboards-web-app/rock-ci-metadata.yaml

feat(twa): Add rock-ci-metadata.yaml

---

pvcviewer-controller/rock-ci-metadata.yaml

feat(pvcviewer): Add rock-ci-metadata.yaml

---

rstudio-tidyverse/rock-ci-metadata.yaml

Closes: https://github.com/canonical/kubeflow-rocks/issues/221
This pr: 
- introduces `rock-ci-metadata.yaml` file for rock integration.
**note:** `workflow_dispatch` is already part of repo
For full file creation steps please refer to [this](https://github.com/canonical/pipelines-rocks/issues/200#issuecomment-3112245114) comment.

feat: `rstudio-tidyverse` create rocks-automation-ci.yaml

---

volumes-web-app/rock-ci-metadata.yaml

feat(vwa): Add rock-ci-metadata.yaml

---

jupyter-web-app/rock-ci-metadata.yaml

feat(jwa): Add rock-ci-metadata.yaml

---

kfam/rock-ci-metadata.yaml

feat(kfam): Add rock-ci-metadata.yaml
