canonical/kubeflow-rocks

kfam/rockcraft.yaml
Adds rockcraft.yaml for kfam, the charm associated to this image is kubeflow-profiles-operator.
1. Build the rock
```
rockcraft pack -v
```
3. Import the rock into a local docker registry
```
sudo skopeo --insecure-policy copy oci-archive:<name of the rock file>.rock docker-daemon:kfam:0.1
```
4. Run the container image
```
docker run --rm kfam:0.1
```
```
2023-05-11T12:08:08.101Z [pebble] Started daemon.
2023-05-11T12:08:08.108Z [pebble] POST /v1/services 6.247989ms 202
2023-05-11T12:08:08.108Z [pebble] Started default services with change 1.
```
Logging into the container and running the service command `/access-management -cluster-admin admin -userid-header kubeflow-userid -userid-prefix ''`
```
root@c5325f89869c:/# /access-management -cluster-admin admin -userid-header kubeflow-userid …
```
=> feat: add kfam rock

admission-webhook/rockcraft.yaml
Add rockcraft yaml for the admission-webhook ROCK.
Upstream here: https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook
Test to run: 
```
rockcraft pack --verbosity=trace
sudo skopeo --insecure-policy copy oci-archive:admission-webhook_v1.7.0_1_amd64.rock docker-daemon:admission-webhook_v1.7.0_1_amd64.rock:rock
docker run admission-webhook_v1.7.0_1_amd64.rock:rock
```
Expected error (as there are no certs in local test)
```
2023-05-09T12:30:39.238Z [pebble] Started daemon.
2023-05-09T12:30:39.253Z [pebble] POST /v1/services 15.006094ms 202
2023-05-09T12:30:39.253Z [pebble] Started default services with change 1.
2023-05-09T12:30:39.268Z [pebble] Service "base-admission-webhook" starting: webhook
2023-05-09T12:30:39.273Z [base-admission-webhook] F0509 …
```
=> KF-2231 Admission webhook Rock

jupyter-pytorch-full/rockcraft.yaml, jupyter-pytorch-full/tests/imports.py, jupyter-pytorch-full/tests/test_access.py, jupyter-pytorch-full/tests/test_imports.py, jupyter-pytorch-full/tests/test_rock.py, jupyter-pytorch-full/tox.ini
Unit tests for Jupyter Pytorch Full ROCK.
These tests verify that all artefacts are in place, that imports can be made in mounted/executed Python script, and that Jupyter Notebook Server is accessible.
- Tests for testing ROCK integrity.
- Commented out some imports in import test as TO-DOs to be addressed during integation stage. Those might not be required to be tested as importes. Integration should verify this.
- Changed /home/jovyan to be owned by _daemon_
- Added notebook server access test.
- Added unit test to test artifacts, imports, and access.
Testing:
```
tox -e unit
```
=> Kf 4075 feat unit tests for jupyter pytorch full rock

jupyter-pytorch-cuda-full/rockcraft.yaml, jupyter-pytorch-cuda-full/tests/imports.py, jupyter-pytorch-cuda-full/tests/test_access.py, jupyter-pytorch-cuda-full/tests/test_imports.py, jupyter-pytorch-cuda-full/tests/test_rock.py, jupyter-pytorch-cuda-full/tox.ini
Unit tests for Jupyter Pytorch Cuda Full ROCK.
These tests verify that all artefacts are in place, that imports can be made in mounted/executed Python script, and that Jupyter Notebook Server is accessible.
- Tests for testing ROCK integrity.
- Commented out some imports in import test as TO-DOs to be addressed during integation stage. Those might not be required to be tested as importes. Integration should verify this.
- Changed /home/jovyan to be owned by _daemon_
- Added notebook server access test.
- Added unit test to test artifacts, imports, and access.
Testing:
```
tox -e unit
```
=> Kf 4075 feat unit tests for jupyter pytorch cuda full rock

notebook-controller/rockcraft.yaml, notebook-controller/tox.ini
Update the `notebook-controller` rock for 1.8, based on the [upstream image](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/notebook-controller/Dockerfile) 
- add tox.ini with charm integration tests
- pin pyjuju to <4.0 in the test requirements due to migration to juju 3 in 1.8
- fix the service name to match the pebble service in the charm
Run the charm integration tests
<details>
<summary>Test logs</summary>
```bash
tox -e integration
integration installed: asttokens==2.4.0,backcall==0.2.0,bcrypt==4.0.1,cachetools==5.3.1,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,cryptography==41.0.4,decorator==5.1.1,exceptiongroup==1.1.3,executing==1.2.0,google-auth==2.23.0,hvac==1.2.1,idna==3.4,iniconf …
```
=> feat: update notebook-controller rock for 1.8

jupyter-web-app/rockcraft.yaml, jupyter-web-app/tox.ini
Update the `jupyter-web-app` rock for 1.8, based on the [upstream image](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/crud-web-apps/jupyter/Dockerfile) 
- add tox.ini with charm integration tests
- pin pyjuju to <4.0 in the test requirements due to migration to juju 3 in 1.8
Run the charm integration tests
<details>
<summary>Test logs</summary>
```bash
tox -e integration
integration create: /home/ubuntu/kubeflow-rocks/jupyter-web-app/.tox/integration
integration installdeps: juju<4.0, pytest, pytest-operator, ops
integration installed: asttokens==2.4.0,backcall==0.2.0,bcrypt==4.0.1,cachetools==5.3.1,certifi==2023.7.22,cffi==1.15.1,charset-normalizer==3.2.0,cryptography==41.0.4,decorator==5.1.1,exception …
```
=> feat: update jupyter-web-app rock for 1.8

jupyter-pytorch-cuda-full/rockcraft.yaml, jupyter-pytorch-cuda-full/tests/test_access.py, jupyter-pytorch-cuda-full/tox.ini
Update the `jupyter-pytorch-cuda-full` rock for 1.8, based on the [upstream image](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/example-notebook-servers/jupyter-pytorch-full/cuda.Dockerfile) 
- pin pyjuju to <4.0 in the unit test requirements due to migration to juju 3 in 1.8
- update kubectl to 1.25
- modify unit to test to wait on the notebook server to start instead of `time.sleep`
Note: the rock was built before running the test
```bash
tox -e unit
unit installed: anyio==4.0.0,asttokens==2.4.0,attrs==23.1.0,backcall==0.2.0,bcrypt==4.0.1,cachetools==5.3.1,certifi==2023.7.22,cffi==1.15.1,charmed-kubeflow-chisme==0.2.0,charset-normalizer==3.2.0,cryptography==41.0.3,decorator==5.1.1,deepdiff==6.2.1,exce …
```
=> feat: update pytorch cuda full rock for 1.8

jupyter-scipy/rockcraft.yaml, jupyter-scipy/tests/test_access.py, jupyter-scipy/tox.ini
Update the `jupyter-scipy` rock for 1.8, based on the [upstream image](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/example-notebook-servers/jupyter-scipy/Dockerfile) 
- pin pyjuju to <4.0 in the unit test requirements due to migration to juju 3 in 1.8
- update kubectl to 1.25
Note: rock was packed before running the tests
```bash
tox -e unit
unit installed: anyio==4.0.0,asttokens==2.4.0,attrs==23.1.0,backcall==0.2.0,bcrypt==4.0.1,cachetools==5.3.1,certifi==2023.7.22,cffi==1.15.1,charmed-kubeflow-chisme==0.2.0,charset-normalizer==3.2.0,cryptography==41.0.4,decorator==5.1.1,deepdiff==6.2.1,exceptiongroup==1.1.3,executing==1.2.0,google-auth==2.23.0,h11==0.14.0,httpcore==0.18.0,httpx==0.25.0,hvac==1.2.1,id …
```
=> feat: update jupyter-scipy rock for 1.8

jupyter-pytorch-full/rockcraft.yaml, jupyter-pytorch-full/tests/test_access.py, jupyter-pytorch-full/tox.ini
Update the `jupyter-pytorch-full` rock for 1.8, based on the [upstream image](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/example-notebook-servers/jupyter-pytorch-full/cpu.Dockerfile) 
- pin pyjuju to <4.0 in the unit test requirements due to migration to juju 3 in 1.8
- update kubectl to 1.25
* microk8s 1.25-strict/stable
* juju 3.1/stable
Note: rock was packed before running the tests
```bash
tox -e unit
unit installed: anyio==4.0.0,asttokens==2.4.0,attrs==23.1.0,backcall==0.2.0,bcrypt==4.0.1,cachetools==5.3.1,certifi==2023.7.22,cffi==1.15.1,charmed-kubeflow-chisme==0.2.0,charset-normalizer==3.2.0,cryptography==41.0.4,decorator==5.1.1,deepdiff==6.2.1,exceptiongroup==1.1.3,executing==1.2.0,google-auth …
```
=> feat: update jupyer pytorch full rock

jupyter-pytorch-cuda-full/rockcraft.yaml, jupyter-pytorch-cuda-full/tests/test_access.py, jupyter-pytorch-full/rockcraft.yaml, jupyter-pytorch-full/tests/test_access.py, jupyter-scipy/rockcraft.yaml, jupyter-scipy/tests/test_access.py, jupyter-tensorflow-cuda-full/rockcraft.yaml, jupyter-tensorflow-cuda-full/tests/test_access.py, jupyter-tensorflow-full/rockcraft.yaml, jupyter-tensorflow-full/tests/test_access.py
Jupyter notebook ROCK are not functionining properly because environment variables are not used in the command AND are set in environment for the service.
More details in: https://github.com/canonical/kubeflow-rocks/issues/54
- Updated environments in all Jupyter notebook server ROCKs to omit envirtonmen variables that need to be set in the Pod environment. Added comment indicating this.
- Updated command to expand environment variables.
=> fix: update command and env variables

centraldashboard/rockcraft.yaml, centraldashboard/tests/test_rock.py, centraldashboard/tox.ini
This commit updates the rockcraft project to match the new requirements from the latest rockcraft version. It also refactors the security requirement to match the latest format in other rock repositories.
Bash is now removed from the image as it is not required and not recommended in production environments, and the build dependency on apt is also removed as it was not used at all. Adding sanity tests in this rock's repository and its corresponding tox file.
Fixes #71
Prerequisites:
* skopeo
* docker
1. Build the rock `rockcraft pack -v`
2. Save the rock as an OCI image in docker's local registry `skopeo --insecure-policy copy oci-archive:kubeflow-central-dashboard_1.7_amd64.rock docker-daemon:cdash:0.1`
3. Run a container with the image and replace the entrypoint with a shell `docker run …
=> chore: update rockcraft project, add sanity test, and tox.ini file

centraldashboard/rockcraft.yaml
In the past, this image used to pass --prefix /app to the npm start command, which is used to force non-global commands to run in the specified folder. We are removing that prefix and instead setting up a working-dir to keep consisdenty with upstream.
Prerequisites:
* skopeo
* docker
1. Build the rock `rockcraft pack -v`
2. Save the rock as an OCI image in docker's local registry `skopeo --insecure-policy copy oci-archive:kubeflow-central-dashboard_1.8_amd64.rock docker-daemon:cdash:0.1`
3. Run a container with the image and replace the entrypoint with a shell `docker run --rm -ti cdash:0.1`
4. Ensure that the service is running correctly:
```
2024-02-14T13:26:52.268Z [serve] "other" is not a supported platform for Metrics
2024-02-14T13:26:52.268Z [serve] Using Profiles service at …
```
=> fix: remove prefix from command and set a working-dir to /app

jupyter-web-app/rockcraft.yaml, jupyter-web-app/tests/test_rock.py, jupyter-web-app/tox.ini
This commit refactors the rockcraft project to use the latest standards for writing rocks. It also adds sanity checks and a tox.ini file so this image gets tested in the CI.
Fixes #80
Prerequisites:
* skopeo
* docker
1. Build the rock `rockcraft pack -v`
2. Save the rock as an OCI image in docker's local registry `skopeo --insecure-policy copy oci-archive:<rock name>.rock docker-daemon:jwa:0.1`
3. Run a container with the image and replace the entrypoint with a shell `docker run --rm -ti jwa:0.1`
4. Ensure the service gets started correctly. NOTE: Because the container image needs kubeconfig and proper expose of a the serving port, the output of the command could have the following errors:
```
kubernetes.config.config_exception.ConfigException: Service host/port is not set. …
```
=> refactor: use latest standards for the jupyter-web-app rock

jupyter-web-app/rockcraft.yaml
The command was incorrectly formatted, resulting in an error: `Error: No application module specified.`
This commit ensures the command actually runs as it is expected from the upstream image.
Prerequisites:
* skopeo
* docker
1. Build the rock `rockcraft pack -v`
2. Save the rock as an OCI image in docker's local registry `skopeo --insecure-policy copy oci-archive:<rock name>.rock docker-daemon:jwa:0.1`
3. Run a container with the image and replace the entrypoint with a shell `docker run --rm -ti jwa:0.1`
4. Ensure the service gets started correctly. NOTE: Because the container image needs kubeconfig and proper expose of a the serving port, the output of the command could have the following errors:
```
kubernetes.config.config_exception.ConfigException: Service host/port is not set. …
```
=> fix: refactor the command to match upstream's

.github/workflows/build_and_publish_rock.yaml, .github/workflows/on_pull_request.yaml, .github/workflows/on_push.yaml, README.md, centraldashboard/tests/test_rock.py, jupyter-pytorch-cuda-full/rockcraft.yaml, jupyter-pytorch-cuda-full/tests/test_rock.py, jupyter-pytorch-full/rockcraft.yaml, jupyter-pytorch-full/tests/test_rock.py, jupyter-scipy/rockcraft.yaml, jupyter-scipy/tests/test_rock.py, jupyter-tensorflow-cuda-full/rockcraft.yaml, jupyter-tensorflow-cuda-full/tests/test_rock.py, jupyter-tensorflow-full/rockcraft.yaml, jupyter-tensorflow-full/tests/test_rock.py
Simply renaming all upper case references of "ROCK" to "rock". Also added a couple of links to the README.md.
=> chore: fix rocks terminology

jupyter-web-app/rockcraft.yaml
IIRC we generally do not include the `rc` part of the tag in the image's version.
Closes #89
=> chore: bump jupyter-web-app to 1.9.0-rc.0

centraldashboard/rockcraft.yaml, centraldashboard/tests/test_rock.py
Diff between [1.8-branch](https://github.com/kubeflow/kubeflow/blob/v1.8-branch/components/centraldashboard/Dockerfile#L36) and [1.9.0-rc.0 tag](https://github.com/kubeflow/kubeflow/blob/v1.9.0-rc.0/components/centraldashboard/Dockerfile#L27) -> https://www.diffchecker.com/JaCMol7i/.
Note that this PR renames also the `name` version since in order to:
1. follow the upstream name as we do in most of our rocks
2. follow the convention where rock directory and rock name are the same
1. `usr/src/app` directory is tested by sanity tests
3. Check that image runs and logs the same with upstream image
```
╰─$ docker run --rm kubeflownotebookswg/centraldashboard:v1.9.0-rc.0                                        
> kubeflow-centraldashboard@0.0.2 start
> npm run serve
> …
```
=> chore: bump centraldashboard image to 1.9.0-rc.0

notebook-controller/rockcraft.yaml
Closes: https://github.com/canonical/kubeflow-rocks/issues/109
I have compared this file https://github.com/kubeflow/kubeflow/blob/v1.9.0/components/notebook-controller/Dockerfile for `v1.9.0` and previous `v1.9.0-rc.0` and there are no differences.
=> Update ntoebook controller for kf 1.9.0

jupyter-web-app/rockcraft.yaml
Closes: https://github.com/canonical/kubeflow-rocks/issues/108
I have compared this file https://github.com/kubeflow/kubeflow/blob/v1.9.0/components/crud-web-apps/jupyter/Dockerfile for `v1.9.0` and previous `v1.9.0-rc.0` and there are no differences.
=> Update web app for kf 1.9.0

centraldashboard/rockcraft.yaml
This PR is a backport of PR #120, and along with [this PR](https://github.com/canonical/kubeflow-dashboard-operator/pull/225) fix issue #104.
=> backport: Change service name to match the name defined in kubeflow-dashboard

centraldashboard/rockcraft.yaml
Change due to canonical/kubeflow-dashboard-operator#222. There's a summary in this comment https://github.com/canonical/kubeflow-dashboard-operator/issues/222#issuecomment-2250042882.
=> centraldashboard: Update permissions of `/root/.npm`

kfam/rockcraft.yaml
Closes: https://github.com/canonical/kubeflow-rocks/issues/132
No changes from 1.8.0 to 1.9.0. But I have:
- changed the service to match the service in the charm
- added security team requirements 
- refactored structure to match other rocks
I have locally tested with the charm and integraiton tests are passing
To test rock:
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:kfam_v1.9.0_amd64.rock docker-daemon:misohu/kfam:v1.9.0
docker run -ti misohu/kfam:v1.9.0 -v
```
expected output:
```
2024-09-11T11:30:26.095Z [pebble] Started daemon.
2024-09-11T11:30:26.127Z [pebble] POST /v1/services 16.163427ms 202
2024-09-11T11:30:26.144Z [pebble] Service "kubeflow-kfam" starting: /access-management
2024-09-11T11:30:26.164Z …
```
=> Udate kfam v1.9.0

profile-controller/rockcraft.yaml
Closes: https://github.com/canonical/kubeflow-rocks/issues/131
No changes from 1.8.0 to 1.9.0. But I have:
- changed the service to match the service in the charm
- added security team requirements 
- refactored structure to match other rocks
I have locally tested with the charm and integraiton tests are passing
To test rock:
```
rockcraft clean && rockcraft pack --verbosity=trace --debug
sudo rockcraft.skopeo --insecure-policy copy oci-archive:profile-controller_v1.9.0_amd64.rock docker-daemon:misohu/profile-controller:v1.9.0
docker run -ti misohu/profile-controller:v1.9.0 -v
```
expected output:
```
2024-09-11T11:25:23.561Z [pebble] Started daemon.
2024-09-11T11:25:23.597Z [pebble] POST /v1/services 16.823408ms 202
2024-09-11T11:25:23.613Z [pebble] Service "kubeflow-profiles" starting: …
```
=> Udate profile-controller v1.9.0

admission-webhook/rockcraft.yaml, admission-webhook/tests/test_rock.py
The path to the webhook binary was modified by #124, causing runtime issues when running the container image with the expected /webhook entrypoint. This commit ensures the binary is placed in the expected path.
Fixes #127
1. Pack `rockcraft pack -v`
2. Save the rock as oci-image `skopeo --insecure-policy copy oci-archive:admission-webhook_v1.9.0_arm64.rock docker-daemon:webhook:0.1`
3. Run the image in a container `docker run --rm -ti --entrypoint /bin/bash webhook:0.1`
4. Verify the `/webhook` binary is present
5. Additionally, this image can be replaced in the charm
=> fix: place the webhook binary in the expected path

admission-webhook/rockcraft.yaml
Closes #136.
This PR simply changes the name of the Pebble service in the `admission-webhook` rock to match the container name defined in the charm operator's code, found [here](https://github.com/canonical/admission-webhook-operator/blob/70384d3e24df19d637a3f74454d4a96f5cd263cc/src/charm.py#L49). This way, only one Pebble service is created.
To test:
- Clone the repository and checkout to this branch
- `cd` to the `admission-webhook` directory and run `tox -e pack`
- `tox -e export-to-docker`
- Clone the `admission-webhook-operator` repository, found [here](https://github.com/canonical/admission-webhook-operator).
- Change the value of `oci-image` in `metadata.yaml` to the image name that was exported (prepending `docker.io/library/` to the image name).
- Run the integration tests with …
=> Update Pebble service name for admission-webhook

pvcviewer-controller/rockcraft.yaml, pvcviewer-controller/tests/test_rock.py, pvcviewer-controller/tox.ini
---
* Added rockcraft.yaml
* Added tests
* Added tox.ini
---
This is re-open request for [this PR](https://github.com/canonical/kubeflow-rocks/pull/130).
Using [pvcviewer-operator](https://github.com/canonical/pvcviewer-operator). Modified: [metadata.yaml](https://github.com/canonical/pvcviewer-operator/blob/main/metadata.yaml#L21). Replaced "docker.io/kubeflownotebookswg/pvcviewer-controller:v1.9.0" with "vyurchenko581/pvcviewer-controller:1.9.0".
Juju status after pvcviwer-operator model is deployed:
```
Model     Controller          Cloud/Region        Version  SLA          Timestamp
kubeflow  microk8s-localhost  microk8s/localhost  3.4.6    unsupported  11:54:49+02:00
App                 Version  Status   Scale  Charm               Channel         Rev  Address         Exposed  Message …
```
=> Added pvcviewer-controller rock

notebook-controller/rockcraft.yaml, notebook-controller/tox.ini
Closes https://warthogs.atlassian.net/browse/KF-6836
Run the upstream image to compare to the rock:
```
docker run docker.io/kubeflownotebookswg/notebook-controller:v1.10.0-rc.0
1.73996405923178e+09    ERROR   controller-runtime.client.config        unable to get kubeconfig        {"error": "invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable", "errorCauses": [{"error": "no configuration has been provided, try setting KUBERNETES_MASTER environment variable"}]}
sigs.k8s.io/controller-runtime/pkg/client/config.GetConfigOrDie
/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/client/config/config.go:153
main.main
/workspace/notebook-controller/main.go:78
runtime.main
/usr/local/go/src/runtime/proc.go:255
```
Run the rock and view …
=> chore: update `notebook-controller rock` to `1.10.0-rc.0`

centraldashboard/rockcraft.yaml, centraldashboard/tox.ini
Closes https://warthogs.atlassian.net/browse/KF-6803
Run the upstream image to compare to the rock:
```
docker run docker.io/kubeflownotebookswg/centraldashboard:v1.10.0-rc.0
> kubeflow-centraldashboard@0.0.2 start
> npm run serve
> kubeflow-centraldashboard@0.0.2 serve
> node dist/server.js
Initializing Kubernetes configuration
Unable to fetch Nodes Error: connect ECONNREFUSED 127.0.0.1:8080
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 8080
}
Unable to fetch Application information: Error: connect ECONNREFUSED 127.0.0.1:8080
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '127.0.0.1',
port: 8080
} …
```
=> chore: update `centraldashboard` rock to `v1.10.0-rc.0`

admission-webhook/rockcraft.yaml, admission-webhook/tox.ini
Closes https://warthogs.atlassian.net/browse/KF-6800
Run the upstream image:
```
docker run docker.io/kubeflownotebookswg/poddefaults-webhook:v1.10.0-rc.0
Unable to find image 'kubeflownotebookswg/poddefaults-webhook:v1.10.0-rc.0' locally
v1.10.0-rc.0: Pulling from kubeflownotebookswg/poddefaults-webhook
3ddae62150f2: Pull complete 
7b5a55846184: Pull complete 
Digest: sha256:ca91fccaa463ca0a7ad42ae682b258aa6b5306adbe4af0444ed2876faa1a3862
Status: Downloaded newer image for kubeflownotebookswg/poddefaults-webhook:v1.10.0-rc.0
F0219 12:44:50.321653       1 config.go:46] config=main.Config{CertFile:"/etc/webhook/certs/cert.pem", KeyFile:"/etc/webhook/certs/key.pem"} Error: open /etc/webhook/certs/cert.pem: no such file or directory
```
Run the rock and get the pebble logs:
``` …
```
=> chore: update `admission-webhook` rock to 1.10.0-rc.0

kfam/rockcraft.yaml
Closes: https://warthogs.atlassian.net/browse/KF-6835
Please note that there haven't been updates to the upstream Dockerfile of this rock, therefore this PR only bumps the version and source to keep it up to date with the versioning system.
=> chore: bump source and version of the `kfam` rock 1.9.0 -> 1.10.0-rc.0

jupyter-scipy/CONTRIBUTING.md, jupyter-scipy/rockcraft.yaml, jupyter-scipy/tests/imports.py, jupyter-scipy/tests/test_access.py, jupyter-scipy/tests/test_imports.py, jupyter-scipy/tests/test_rock.py, jupyter-scipy/tox.ini
Closes: https://warthogs.atlassian.net/browse/KF-6997
Major changes in upstream:
- Version updates basically in every components
- User and group revamp
- Jupyter initialisation procedure
Other changes:
- I have changed the tests in the rock with the same approach we use in different rocks
**How to review**
- You can run each tox environment to pack export to docker and to run the sanity tests (sanity tests are testing also that the jupyter lab is accessible).
- You can also run the server locally with 
```
docker run -p 8888:8888 misohu/jupyter-scipy:1.10.0 exec /opt/conda/bin/jupyter lab --notebook-dir="/home/jovyan" --ip=0.0.0.0 --no-browser --port=8888 --ServerApp.token="" --ServerApp.password="" --ServerApp.allow_origin="*" --ServerApp.base_url="/" …
```
=> feat: update `jupyter-scipy` rock for `1.10.0-rc`

pvcviewer-controller/rockcraft.yaml, pvcviewer-controller/tox.ini
Small note on removing `run-user: _daemon`: There is an issue when running pebble as `_daemon_` and running a service as a non-root user, where we get an error similar to this:
```
2025-02-10T14:08:30.863Z [pebble] Change 1 task (Start service "myapp") failed: cannot start service: fork/exec /bin/whoami: operation not permitted
```
For example, we encountered this during the creation of the `torchserve-kfs` rock in the `kserve-rocks` repository. The suggestion from the rockcraft team was to remove `run-user`, as mentioned in [this comment](https://github.com/canonical/kserve-rocks/pull/106#issuecomment-2648921069)
First pull and run the upstream image:
```
docker pull kubeflownotebookswg/pvcviewer-controller:v1.10.0-rc.1
docker run --rm -it …
```
=> chore: Update pvcviewer-controller rock to 1.10-rc.1

admission-webhook/rockcraft.yaml
Closes https://warthogs.atlassian.net/browse/KF-7061
The only change in upstream is https://github.com/kubeflow/kubeflow/pull/7686 to use non-root user.
I have removed the part of creating `ubuntu` user and we can make sure to run as non-root by setting `user` in the pebble layer as `_daemon_` based on the findings in https://github.com/canonical/kfp-operators/issues/675.
=> chore: update admission webhook rock to 1.10.0-rc.1

tensorboard-controller/rockcraft.yaml
This commit upgrades the tensorboard-controller rock in preparation for a new release.
Fixes #182
No changes in upstream Dockerfiles, just tag.
=> chore: upgrade tensorboard-controller 1.10.0-rc.0 -> 1.10.0-rc.1

volumes-web-app/rockcraft.yaml
This commit upgrades the volumes-web-app rock in preparation for a new release.
Fixes #184
No changes in the upstream Dockerfiles, just the tag.
=> chore: upgrade volumes-web-app 1.10.0-rc.0 -> 1.10.0-rc.1

tensorboard-controller/rockcraft.yaml, tensorboards-web-app/rockcraft.yaml
Closes https://warthogs.atlassian.net/browse/KF-7154
No changes were made to the images, just updated the version.
For reference see the Dockerfiles for [controller](https://github.com/kubeflow/kubeflow/blob/v1.10.0/components/tensorboard-controller/Dockerfile) and [web-app](https://github.com/kubeflow/kubeflow/blob/v1.10.0/components/crud-web-apps/tensorboards/Dockerfile)
=> chore: upgrade tensorboards rocks to v1.10.0

centraldashboard/rockcraft.yaml
No updates [diff](https://www.diffchecker.com/rEkMdY9L/)
=> chore: update central-dashboard to v1.10.0

jupyter-pytorch-full/rockcraft.yaml, jupyter-scipy/CONTRIBUTING.md, jupyter-scipy/rockcraft.yaml, jupyter-web-app/rockcraft.yaml, notebook-controller/rockcraft.yaml
Closes https://warthogs.atlassian.net/browse/KF-7152
There were no changes to the images from `v1.10.0-rc.1`, just updated the version.
See [the tag diff](https://github.com/kubeflow/kubeflow/compare/v1.10.0-rc.1...v1.10.0) for reference.
Note than `jupyter-tensorflow-full` rock is being updated in https://github.com/canonical/kubeflow-rocks/pull/195.
=> chore: upgrade notebook rocks to v1.10.0

centraldashboard/rockcraft.yaml
Revert commit in upstream code that breaks the `logout` function for
oidc-authservice.
Fix canonical/bundle-kubeflow#1259
For testing, refer to the issue. The image from this PR has been pushed to `docker.io/orfeask/kubeflow-centraldashboard:1.10.0-dirty`
CI is fixed in https://github.com/canonical/kubeflow-rocks/pull/248.
=> fix(dashboard): Fix logout button for oidc-authservice

profile-controller/rock-ci-metadata.yaml
=> feat(profile-controller): Add rock-ci-metadata.yaml
